---

language: node_js

node_js:
  - 10.17.0

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev libpeas-dev libpeas-1.0-0

install:
  - npm i -g @elementaryos/houston

script:
  - houston ci
